### ISSUE TITLE
Goodby Intobox!

### ISSUE THREAD

**Issue by keitakawamoto** [balloonbros/Intobox#5]
- [x] GitHub Pages作成（このリポジトリにgh-pasesブランチ作成）
- [x] intobox.inドメインをGitHub Pagesに向ける
- [x] さくらVPS解約
- [x] GitHub PagesにCloseページをpush

**Comment by keitakawamoto** [comment]
![image](https://cloud.githubusercontent.com/assets/1661325/9958144/03c15752-5e42-11e5-917a-d153495e874e.png)

メール受信待ち

**Comment by keitakawamoto** [comment]
解約完了

![image](https://cloud.githubusercontent.com/assets/1661325/9958376/0b6397f2-5e44-11e5-8edd-bfa9c1e36ff2.png)

![image](https://cloud.githubusercontent.com/assets/1661325/9958412/81a2c1a4-5e44-11e5-951b-e449ca714e03.png)

**Comment by keitakawamoto** [comment]
ドメインのDNS設定をさくらからGitHub Pagesに変更した。

![image](https://cloud.githubusercontent.com/assets/1661325/9958631/ff33b7ca-5e46-11e5-8e61-7760da6ae02a.png)

**Comment by keitakawamoto** [comment]
ドメインをgh-pagesに向けた

![image](https://cloud.githubusercontent.com/assets/1661325/9958958/3479e320-5e4a-11e5-8605-7c824659d59e.png)

**Comment by keitakawamoto** [comment]
http://intobox.in/ いけた
httpsでアクセスするとおかしい https://intobox.in/

**Comment by keitakawamoto** [comment]
- https://github.com/balloonbros/Intobox/commit/4fbbadee121639e4bba6decbccd1e21be4c84ece
- https://github.com/balloonbros/Intobox/commit/e86225a264293d4943d516cd66118285f0a2c812

いろいろ試したものの、gh-pagesでは解決策が見当たらないのでhttpsからのアクセスについてはあきらめる。

**Comment by keitakawamoto** [comment]
Closeページ完了。

![image](https://cloud.githubusercontent.com/assets/1661325/10246417/06d3e9e0-694c-11e5-8d29-121e96f8e846.png)

さようなら
ありがとう
Intobox。
お前がいたから今の俺たちがある。

**Comment by shoyan** [comment]
よい思い出をありがとう、Intobox!

**Comment by keitakawamoto** [comment]
http://balloonbros.cc/Intobox/
